# the 1024 to be scaled up if aiming for over 500 as well as the amount of containers
events { 
    worker_connections 1024; 
}

# L7 Load balancing with least connections algorithm implemented here. We can instead use a ip_hash instead if we want for later
# IP hashing would make sure that the same user ends up at the same docker container every time.
http {
    upstream flask_cluster {
        least_conn;
        server app:5000; 
    }

    server {
        listen 80;
        server_name short.urlshortener-mlh.xyz;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name short.urlshortener-mlh.xyz;

        ssl_certificate /etc/letsencrypt/live/short.urlshortener-mlh.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/short.urlshortener-mlh.xyz/privkey.pem;

        location / {
            # Send all incoming traffic to the pool we defined above
            proxy_pass http://flask_cluster;            
            # Pass along the original HTTP headers (Crucial for L7!)
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}